### ISSUE TITLE
Error on example data from group function

### ISSUE THREAD

**Issue by dence** [bschiffthaler/BatchMap#1]
Hi, when I try to find linkage groups with the example data from this repository, I get an error. 
My commands are: 
input_file <- "test_download//BatchMap/inst/example/sim7.5k.txt.gz"
Fr1_megs <- read.outcross2(input_file)
bins <- find.bins(Fr1_megs, exact = FALSE)
outcross_clean <- create.data.bins(Fr1_megs, bins)
twopt_table <- rf.2pts(outcross_clean,LOD=6,max.rf=0.4)
tmp <- make.seq(twopt_table,"all")
LGs_clean <- group(tmp)

The error that I get is: Error in if (cl == "outcross") { : missing value where TRUE/FALSE needed

My guess is that there is something in the formatting or whitespace of the input file since that is where I have had trouble before. 

I made sure to install the latest version from github tonight too. 

Thanks,
Daniel

**Comment by bschiffthaler** [comment]
I cannot reproduce this in a clean install of R 4. Can you please try to explicitly scope `BatchMap` functions:

```
input_file <- "~/sim7.5k.txt.gz"
Fr1_megs <- BatchMap::read.outcross2(input_file)
bins <- BatchMap::find.bins(Fr1_megs, exact = FALSE)
outcross_clean <- BatchMap::create.data.bins(Fr1_megs, bins)
twopt_table <- BatchMap::rf.2pts(outcross_clean, LOD = 6, max.rf = 0.4)
tmp <- BatchMap::make.seq(twopt_table, "all")
LGs_clean <- BatchMap::group(tmp)
```

In addition, can you add your `sessionInfo()` from the _R session that has this bug_.
Thanks

**Comment by dence** [comment]
[sessionInfo.txt](https://github.com/bschiffthaler/BatchMap/files/6102028/sessionInfo.txt)

Hi, Explicitly scoping the batchmap functions resolve the error. I've attached my session info in case that will still be helpful. I'm having trouble getting some of my own data to run. I'll post a separate issue for that since the error is different. 

Thanks,
Daniel
